@startuml

enum GameStatus {
    Lobby,
    Ongoing,
    Winner,
    Looser,
}

enum Game {
    ViewGewinnt
}

enum PayloadType{
    Login,
    Game,
    Quit,
    Error,
}

enum Error {
    Disconnect,
    Timeout,
    InvalidMessage,
}

class BasePayload{
    + message-type: PayloadType;
    + sender-id: Guid;
}


GamePayload -u-|> BasePayload
GamePayload ..> GameStatus
GamePayload ..> PayloadType
class GamePayload{
    + status: GameStatus;
    + field: int[][];
}

ErrorPayload -u-|> BasePayload
ErrorPayload ..> Error
ErrorPayload ..> PayloadType
class ErrorPayload{
    + error-code: Error;
    + message: string;
}


LoginPayload -u-|> BasePayload
LoginPayload ..> Game
LoginPayload ..> PayloadType
class LoginPayload{
    + game: Game;
    + timestamp: DateTime;
}

QuitPayload -u-|> BasePayload
QuitPayload ..> PayloadType
class QuitPayload{
}
@enduml